#ifndef OHD_TYPES_HPP
#define OHD_TYPES_HPP

typedef enum
{
    OHD_STATE_UNDEFINED = 0,
    OHD_STATE_UNINITIALIZED,
    OHD_STATE_STARTUP,
    OHD_STATE_RUNNING,
    OHD_STATE_ERROR,
} OHD_state_t;

typedef enum
{
    OHD_EVENT_UNDEFINED = 0,
    OHD_EVENT_NONE,
    OHD_EVENT_RUN_REQUEST,
    OHD_EVENT_STARTUP_SUCCESSFUL,
    OHD_EVENT_ERROR
} OHD_event_t;

#endif /* OHD_TYPES_HPP */